AWSTemplateFormatVersion: '2010-09-09'
Description: Static Website Infrastructure
Parameters:
  BucketName:
    Description: Name for the S3 bucket
    Type: String
    Default: YourBucketName # Replace with your desired bucket name
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead # Make objects publicly accessible
      WebsiteConfiguration:
        IndexDocument: index.html # Default index document
        ErrorDocument: error.html # Default error document
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 86400
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Restrictions:
          GeoRestriction:
            RestrictionType: none
Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL of the S3 bucket website endpoint
